name: firebase_auth_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
#auth
  firebase_auth: ^3.3.17
  firebase_core: ^1.16.0
  google_sign_in: ^5.3.0
#state management
  flutter_bloc: ^8.0.1
#code generation
  meta: ^1.7.0
  equatable: ^2.0.3
  injectable: ^1.5.3
#dependency injection
  get_it: ^7.2.0
#local data store
  shared_preferences: ^2.0.13


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
#code generation
  build_runner: ^2.1.8
  injectable_generator: ^1.5.3


flutter:

  uses-material-design: true

